services:
  # Backend API Service
  - type: web
    name: wallet-app-backend-bj9j
    runtime: node
    plan: free
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5002
      - key: JWT_SECRET
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: CORS_ORIGIN
        value: https://wallet-app-frontend-cxal.onrender.com

  # Frontend Service
  - type: web
    name: wallet-app-frontend-cxal
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://wallet-app-backend-bj9j.onrender.com/api
